# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace # removes whitespace
    -   id: end-of-file-fixer   # adds empty stringto end of file
    -   id: check-yaml  # structures yamls
    -   id: check-added-large-files #
