# Dockerfile.test

FROM python:3.11 as base

WORKDIR /pythonExercise1

COPY app/ app/
COPY tests/test_main.py .

# Use 'base' stage for running tests
FROM base as test

# Add testing-specific dependencies
COPY requirements-test.txt .
RUN pip install -r requirements-test.txt

CMD ["pytest", "test_main.py"]
