version: '3.4'

services:
  my-python-app:
    container_name: my-python-app
    build:
      context: .
      target: dev
    image: my-python-app
    ports:
      - "5673:5673"
    volumes:
      - ./app:/pythonExercise1/app
      - ./tests:/pythonExercise1/tests
    command: ${BASE_COMMAND} ${BASE_ARGS}
