version: "3"

tasks:
  build:
    cmds:
      - docker-compose -f docker-compose.yml build

  up:
    env:
      BASE_COMMAND: '{{if eq .USE_DEBUGPY "true"}}/tmp/debugpy --listen 127.0.0.1:5673 --wait-for-client main.py{{else}}{{end}}'
    cmds:
      - docker-compose -f docker-compose.yml up

  build-test:
    cmds:
      - docker-compose -f docker-compose.test.yml build

  up-test:
    cmds:
      - docker-compose -f docker-compose.test.yml up
