version: "3"

tasks:
  build:
    cmds:
      - docker-compose -f docker-compose.yml build

  up:
    env:
      BASE_COMMAND: '{{if eq .USE_DEBUGPY "true"}}/tmp/debugpy --listen 0.0.0.0:5673 --wait-for-client app/main.py{{else}}{{end}}'
    cmds:
      - docker-compose -f docker-compose.yml up

  build-test:
    cmds:
      - docker-compose -f docker-compose.test.yml build

  up-test:
    env:
      BASE_COMMAND: '{{if eq .USE_DEBUGPY "true"}}/tmp/debugpy --listen 0.0.0.0:5673 --wait-for-client tests/test_main.py{{else}}{{end}}'
    cmds:
      - docker-compose -f docker-compose.test.yml up

  build-all:
    cmds:
      - docker-compose -f docker-compose.yml -f docker-compose.test.yml build
