# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:

            # removes extra whitespaces
    -   id: trailing-whitespace

            # adds empty string at the end of each file
    -   id: end-of-file-fixer

            # checks files are properly structured
    -   id: check-yaml
    -   id: check-toml
    -   id: check-json
    -   id: check-xml

            # doesn't allow committing of large files >500Kb
    -   id: check-added-large-files

            # prohibits unresolved conflicts
    -   id: check-merge-conflict

            # validates .py files
    -   id: check-ast

            # double quotes to single quotes
    -   id: double-quote-string-fixer

            # writes debug statements for pdb and ipdb
    -   id: debug-statements

